"""
Integrate per-annotator annotation outputs.

This script reads the assignment manifests generated by ``scripts/orchestrate.py``,
loads every annotator's completed document outputs, computes exact-match
pairwise inter-annotator agreement (IAA) on the document-level outputs, and
auto-merges documents where all assigned annotators produced the same final
JSON output.

Usage:
    python scripts/integrate_annotations.py
    python scripts/integrate_annotations.py --config annotation_config.yaml
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from collections import Counter, defaultdict
from itertools import combinations
from pathlib import Path
from typing import Any

import yaml


def load_config(config_path: str) -> dict[str, Any]:
    """Load and validate the integration config."""
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f) or {}

    required_keys = ["annotators", "output_dir"]
    for key in required_keys:
        if key not in config:
            print(f"ERROR: Missing required key '{key}' in config.")
            sys.exit(1)

    annotators = config["annotators"]
    if not annotators:
        print("ERROR: At least one annotator must be defined.")
        sys.exit(1)

    return config


def resolve_config_path(config_path: str) -> Path:
    """Resolve config path relative to CWD or project root."""
    candidate = Path(config_path)
    if candidate.is_absolute() and candidate.exists():
        return candidate

    if candidate.exists():
        return candidate.resolve()

    project_root = Path(__file__).resolve().parent.parent
    fallback = project_root / config_path
    if fallback.exists():
        return fallback.resolve()

    print(f"ERROR: Config file not found: {config_path}")
    sys.exit(1)


def canonicalize_value(value: Any) -> Any:
    """Normalize JSON-like values so semantically identical outputs compare equal."""
    if isinstance(value, dict):
        return {
            key: canonicalize_value(inner)
            for key, inner in sorted(value.items())
            if key != "event_id"
        }
    if isinstance(value, list):
        return [canonicalize_value(item) for item in value]
    return value


def annotation_signature(events: list[dict[str, Any]]) -> list[str]:
    """Return a stable signature for a document's annotation output."""
    normalized_events = [canonicalize_value(event) for event in events]
    return sorted(
        json.dumps(event, sort_keys=True, ensure_ascii=False)
        for event in normalized_events
    )


def annotation_label(events: list[dict[str, Any]]) -> str:
    """Return a hashable label for agreement metrics."""
    return json.dumps(annotation_signature(events), ensure_ascii=False)


def load_json_list(path: Path) -> list[Any]:
    """Load a JSON file that must contain a list."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError("expected a JSON list")

    return data


def load_optional_json_dict(path: Path) -> dict[str, Any] | None:
    """Load an optional JSON file that must contain an object."""
    if not path.exists():
        return None

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict):
        raise ValueError("expected a JSON object")

    return data


def load_source_text(project_root: Path, doc_id: str) -> str | None:
    """Load the original source text for a document when available."""
    source_filename = doc_id.replace(".json", ".txt")
    source_path = project_root / "data" / "sample" / "source" / source_filename
    if not source_path.exists():
        return None

    with open(source_path, "r", encoding="utf-8") as f:
        return f.read()


def load_assignments(assignments_dir: Path) -> dict[str, list[str]]:
    """Load per-annotator assignment manifests."""
    if not assignments_dir.exists():
        raise FileNotFoundError(
            f"Assignments directory not found: {assignments_dir}. "
            "Run scripts/orchestrate.py first."
        )

    assignments: dict[str, list[str]] = {}
    for manifest_path in sorted(assignments_dir.glob("*.json")):
        docs = load_json_list(manifest_path)
        assignments[manifest_path.stem] = sorted(str(doc) for doc in docs)

    return assignments


def build_doc_to_annotators(assignments: dict[str, list[str]]) -> dict[str, list[str]]:
    """Invert annotator manifests into doc -> annotators mapping."""
    doc_to_annotators: dict[str, list[str]] = defaultdict(list)
    for annotator_id, docs in assignments.items():
        for doc_id in docs:
            doc_to_annotators[doc_id].append(annotator_id)

    return {doc_id: sorted(annotators) for doc_id, annotators in doc_to_annotators.items()}


def _safe_rate(numerator: int, denominator: int) -> float | None:
    if denominator == 0:
        return None
    return numerator / denominator


def _compute_pairwise_agreement_metrics(
    pair: str,
    stats: dict[str, Any],
) -> dict[str, Any]:
    """Summarize exact pairwise agreement for one annotator pair."""
    left, right = pair.split(" :: ")
    compared_docs = stats["compared_docs"]
    agreed = stats["agreed"]
    observed_agreement = _safe_rate(agreed, compared_docs)

    label_counts = stats["label_counts"]
    left_counts: Counter[str] = label_counts.get(left, Counter())
    right_counts: Counter[str] = label_counts.get(right, Counter())

    return {
        "agreed": agreed,
        "compared_docs": compared_docs,
        "iaa": observed_agreement,
        "observed_agreement": observed_agreement,
        "labels_observed": len(set(left_counts) | set(right_counts)),
    }


def integrate_project(config_path: str) -> dict[str, Any]:
    """Run annotation integration and return the generated report."""
    resolved_config_path = resolve_config_path(config_path)
    config = load_config(str(resolved_config_path))
    project_root = resolved_config_path.parent

    output_dir = (project_root / config["output_dir"]).resolve()
    assignments_dir = output_dir / "assignments"
    results_dir = output_dir / "results"
    integration_dir = output_dir / "integration"
    merged_dir = integration_dir / "merged"
    conflicts_dir = integration_dir / "conflicts"

    assignments = load_assignments(assignments_dir)
    doc_to_annotators = build_doc_to_annotators(assignments)

    integration_dir.mkdir(parents=True, exist_ok=True)
    if merged_dir.exists():
        shutil.rmtree(merged_dir)
    merged_dir.mkdir(parents=True, exist_ok=True)
    if conflicts_dir.exists():
        shutil.rmtree(conflicts_dir)
    conflicts_dir.mkdir(parents=True, exist_ok=True)

    errors: list[str] = []
    pair_stats: dict[str, dict[str, Any]] = defaultdict(
        lambda: {"agreed": 0, "compared_docs": 0, "label_counts": {}}
    )

    annotator_completion: dict[str, Any] = {}
    for annotator in config["annotators"]:
        annotator_id = annotator["id"]
        assigned_docs = assignments.get(annotator_id, [])
        annotator_results_dir = results_dir / annotator_id
        review_state_dir = annotator_results_dir / "review_state"

        completed_docs = 0
        invalid_docs: list[str] = []
        unresolved_docs: list[str] = []
        for doc_id in assigned_docs:
            result_path = annotator_results_dir / doc_id
            if not result_path.exists():
                continue

            try:
                load_json_list(result_path)
                completed_docs += 1
            except Exception as exc:  # pragma: no cover - exercised by doc-level reporting
                invalid_docs.append(doc_id)
                errors.append(f"{annotator_id}/{doc_id}: {exc}")

            try:
                review_state_path = review_state_dir / doc_id
                review_state = load_optional_json_dict(review_state_path)
                if review_state and review_state.get("unresolved_pair_count", 0) > 0:
                    unresolved_docs.append(doc_id)
            except Exception as exc:  # pragma: no cover - exercised by doc-level reporting
                errors.append(f"{annotator_id}/review_state/{doc_id}: {exc}")

        unexpected_files: list[str] = []
        if annotator_results_dir.exists():
            expected_docs = set(assigned_docs)
            for file_path in sorted(annotator_results_dir.glob("*.json")):
                if file_path.name == "output.json":
                    continue
                if file_path.name not in expected_docs:
                    unexpected_files.append(file_path.name)

        annotator_completion[annotator_id] = {
            "name": annotator.get("name", annotator_id),
            "assigned_docs": len(assigned_docs),
            "completed_docs": completed_docs,
            "completion_rate": _safe_rate(completed_docs, len(assigned_docs)),
            "invalid_docs": invalid_docs,
            "unresolved_docs": sorted(unresolved_docs),
            "unexpected_result_files": unexpected_files,
        }

    documents: list[dict[str, Any]] = []
    auto_merged_docs = 0
    fully_annotated_docs = 0
    missing_docs = 0
    disagreement_docs = 0
    total_pairwise_agreements = 0
    total_pairwise_comparisons = 0

    for doc_id in sorted(doc_to_annotators):
        assigned_annotators = doc_to_annotators[doc_id]
        loaded_annotations: dict[str, list[Any]] = {}
        loaded_review_states: dict[str, dict[str, Any]] = {}
        missing_annotators: list[str] = []
        invalid_annotators: list[str] = []
        unresolved_annotators: list[str] = []

        for annotator_id in assigned_annotators:
            annotator_results_dir = results_dir / annotator_id
            result_path = annotator_results_dir / doc_id
            if not result_path.exists():
                missing_annotators.append(annotator_id)
                continue

            try:
                loaded_annotations[annotator_id] = load_json_list(result_path)
            except Exception as exc:
                invalid_annotators.append(annotator_id)
                errors.append(f"{annotator_id}/{doc_id}: {exc}")
                continue

            review_state_path = annotator_results_dir / "review_state" / doc_id
            try:
                review_state = load_optional_json_dict(review_state_path)
            except Exception as exc:
                invalid_annotators.append(annotator_id)
                errors.append(f"{annotator_id}/review_state/{doc_id}: {exc}")
                continue

            if review_state:
                loaded_review_states[annotator_id] = review_state
                if review_state.get("unresolved_pair_count", 0) > 0:
                    unresolved_annotators.append(annotator_id)

        pairwise_details: list[dict[str, Any]] = []
        pairwise_agreement = None
        unanimous_agreement = False
        merged_output = None
        conflict_bundle = None
        conflict_reasons: list[str] = []

        if missing_annotators or invalid_annotators:
            status = "pending"
            missing_docs += 1
        else:
            fully_annotated_docs += 1
            signatures = {
                annotator_id: annotation_signature(events)
                for annotator_id, events in loaded_annotations.items()
            }
            labels = {
                annotator_id: annotation_label(events)
                for annotator_id, events in loaded_annotations.items()
            }
            annotator_pairs = list(combinations(sorted(loaded_annotations), 2))

            if annotator_pairs:
                agreements = []
                for left, right in annotator_pairs:
                    agreed = signatures[left] == signatures[right]
                    agreements.append(1 if agreed else 0)
                    pairwise_details.append(
                        {"annotators": [left, right], "agreed": agreed}
                    )

                    key = " :: ".join(sorted((left, right)))
                    pair_stats[key]["compared_docs"] += 1
                    pair_stats[key]["agreed"] += 1 if agreed else 0
                    pair_stats[key]["label_counts"].setdefault(left, Counter())[labels[left]] += 1
                    pair_stats[key]["label_counts"].setdefault(right, Counter())[labels[right]] += 1

                total_pairwise_agreements += sum(agreements)
                total_pairwise_comparisons += len(agreements)
                pairwise_agreement = sum(agreements) / len(agreements)
                unanimous_agreement = all(agreements)
            else:
                unanimous_agreement = True

            if unresolved_annotators:
                status = "conflict"
                disagreement_docs += 1
                conflict_reasons.append("unresolved_flagged_pairs")
                if not unanimous_agreement:
                    conflict_reasons.append("annotator_disagreement")
            elif unanimous_agreement:
                status = "auto_merged"
                auto_merged_docs += 1
                first_annotator = sorted(loaded_annotations)[0]
                merged_output = str((merged_dir / doc_id).resolve())
                with open(merged_dir / doc_id, "w", encoding="utf-8") as f:
                    json.dump(loaded_annotations[first_annotator], f, indent=2, ensure_ascii=False)
            else:
                status = "conflict"
                disagreement_docs += 1
                conflict_reasons.append("annotator_disagreement")

        if status == "conflict":
            conflict_bundle_path = conflicts_dir / doc_id
            conflict_bundle = str(conflict_bundle_path.resolve())
            conflict_payload = {
                "doc_id": doc_id,
                "status": status,
                "conflict_reasons": conflict_reasons,
                "source_text": load_source_text(project_root, doc_id),
                "assigned_annotators": assigned_annotators,
                "pairwise_agreement": pairwise_agreement,
                "pairwise_details": pairwise_details,
                "candidates": [
                    {
                        "annotator_id": annotator_id,
                        "events": loaded_annotations.get(annotator_id, []),
                        "review_state": loaded_review_states.get(annotator_id),
                        "result_path": str((results_dir / annotator_id / doc_id).resolve()),
                    }
                    for annotator_id in assigned_annotators
                    if annotator_id in loaded_annotations
                ],
            }
            with open(conflict_bundle_path, "w", encoding="utf-8") as f:
                json.dump(conflict_payload, f, indent=2, ensure_ascii=False)

        documents.append(
            {
                "doc_id": doc_id,
                "assigned_annotators": assigned_annotators,
                "completed_annotators": sorted(loaded_annotations),
                "missing_annotators": missing_annotators,
                "invalid_annotators": invalid_annotators,
                "unresolved_annotators": sorted(unresolved_annotators),
                "status": status,
                "conflict_reasons": conflict_reasons,
                "pairwise_agreement": pairwise_agreement,
                "unanimous_agreement": unanimous_agreement,
                "pairwise_details": pairwise_details,
                "merged_output": merged_output,
                "conflict_bundle": conflict_bundle,
            }
        )

    pairwise_iaa_by_pair = {}
    for pair, stats in sorted(pair_stats.items()):
        pair_metrics = _compute_pairwise_agreement_metrics(pair, stats)
        pairwise_iaa_by_pair[pair] = pair_metrics

    report = {
        "comparison_basis": "exact_match_document_outputs",
        "config_path": str(resolved_config_path),
        "output_dir": str(output_dir),
        "integration_dir": str(integration_dir),
        "summary": {
            "total_documents": len(documents),
            "fully_annotated_documents": fully_annotated_docs,
            "documents_pending_annotations": missing_docs,
            "documents_with_disagreement": disagreement_docs,
            "auto_merged_documents": auto_merged_docs,
            "overall_pairwise_iaa": _safe_rate(
                total_pairwise_agreements, total_pairwise_comparisons
            ),
            "unanimous_doc_rate": _safe_rate(auto_merged_docs, fully_annotated_docs),
        },
        "annotator_completion": annotator_completion,
        "pairwise_iaa_by_pair": pairwise_iaa_by_pair,
        "documents": documents,
        "errors": errors,
    }

    report_path = integration_dir / "iaa_report.json"
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print("\n" + "=" * 60)
    print("  INTEGRATION SUMMARY")
    print("=" * 60)
    print(f"  Total documents:           {report['summary']['total_documents']}")
    print(f"  Fully annotated:           {report['summary']['fully_annotated_documents']}")
    print(f"  Pending annotations:       {report['summary']['documents_pending_annotations']}")
    print(f"  Docs with disagreement:    {report['summary']['documents_with_disagreement']}")
    print(f"  Auto-merged documents:     {report['summary']['auto_merged_documents']}")

    overall_iaa = report["summary"]["overall_pairwise_iaa"]
    if overall_iaa is None:
        print("  Overall pairwise IAA:      n/a")
    else:
        print(f"  Overall pairwise IAA:      {overall_iaa:.3f}")

    print("-" * 60)
    print(f"  Report written to:         {report_path}")
    print(f"  Auto-merged outputs:       {merged_dir}")
    print("=" * 60 + "\n")

    return report


def main():
    parser = argparse.ArgumentParser(
        description="Integrate per-annotator outputs and compute exact-match pairwise IAA."
    )
    parser.add_argument(
        "--config",
        default="annotation_config.yaml",
        help="Path to annotation config YAML (default: annotation_config.yaml)",
    )
    args = parser.parse_args()

    integrate_project(args.config)


if __name__ == "__main__":
    main()
